---
title: "Time Series Analysis 0316"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Moving average smoothing practice
```{r MA}
data("AirPassengers")
m3 = filter(AirPassengers, filter=rep(1/3,3)) #가중치를 1/3로 동일하게
m6 = filter(AirPassengers, filter=rep(1/6,6))
m12 = filter(AirPassengers, filter=rep(1/12,12))

#비정상성데이터(추세+계절성) - 계절변동의 분산이 커지고 있다
plot(AirPassengers, main="AirPassengers: original data") 
plot(m3, main="3-point moving average")
plot(m6, main="6-point moving average")
plot(m12, main="12-point moving average") #추세만 남게 된다

#moving average - 큰 범위의 추세값은 제거할 수 있게 된다
```

## R example : 4point MA for dd1
```{r}
library(forecast)
dd1 = matrix(c(1342,1442,1252,1343,1425,1362,1456,1272,1243,
               1359,1412,1253,1201,1478,1322,1406,1254,1289,1497,1208))
dd1.ts = ts(data=dd1, start=c(2006,1), frequency=4)
dd1.ts

ff=filter(dd1.ts, filter=rep(1,4)/4, method="convolution", sides=1) #다항이동평균 - 2006 이전값이 없어 3분기까지 NA
plot(dd1.ts, main="dd1.ts with simple moving average smoothing") +
  lines(ff, col="red", lty=2, lwd=2) + #red; 다항이동평균값
  abline(h=mean(dd1), col="blue") #blue; dd1 data의 평균

#잔차 - smoothing에 따른 모델링이 dd1.ts를 잘 설명하였는가: 예측오차값이 작고 추세가 없어야 한다
res=ff[-1:-3,]-dd1.ts[-1:-3,] #ff: 2006 3분기까지 데이터 없으므로 dd1.ts도 같이 뺀다
tsdisplay(res, main="Residuals by MA(4) for dd1") #잔차의 시계열분포, ACF, PACF 함께 출력
                                                  #잔차가 정상성을 보임을 알 수 있다.
Box.test(res, type="Box-Pierce") #귀무가설:TS is independent(독립성이 있다)
                                 #p-value가 0.3229이므로 귀무가설 기각하지 못한다.
                                 #즉, 잔차가 자기상관이 없다
```

## double moving average smoothing (=이중이동평균=선형이동평균)
```{r}
ff1 = filter(dd1.ts, filter=rep(1,3)/3, method="convolution", sides=1)
ff2 = filter(ff1, filter=rep(1,3)/3, method="convolution", sides=1) #한번더 smoothing

plot(dd1.ts, main="dd1.ts with simple moving average smoothing") +
  lines(ff2, col="red", lty=2, lwd=2) + #ff1보다 좀더 smoothing
  abline(h=mean(dd1), col="blue")

res = ff2[-1:-3,]-dd1.ts[-1:-3,]
tsdisplay(res, main="Residuals by double MA smoothing")
Box.test(res, type="Box-Pierce") #H0 : TS is independent
```

## double moving average(2nd method)
```{r}
mm1 = ma(dd1.ts, order=4, centre=F) #산정기준 중심이 없는 경우 - t번째 뒤의 4개(t, t-1, t-2, t-3)
mm3 = ma(dd1.ts, order=3, centre=T) #산정기준 중심이 있는 경우 - t번째 앞,뒤로 3개(t-1, t, t+1)
mm4 = ma(mm3, order=3, centre=T) #이중이동평균

res3 = mm4-dd1.ts 
Box.test(res3)

#forecast - 미래의 2개 예측(h=2)
#band(lo80, hi80, lo95, hi95를 가지고 예측 범위 표현)
plot(forecast(mm1, h=2), main="forecast simple MA") #missing_values 존재
plot(forecast(mm4, h=2), main="forecast simple MA")

f1 = forecast(mm1, h=1)
f1
f4 = forecast(mm4, h=1)
f4

#실제값과 예측값 정확도 - RMSE가 작을수록 정확하다
accuracy(f1)
accuracy(f4)
```

## Exponential Smoothing method 
 - 가장 최근의 관측값에 가장 큰 가중치를 부여(alpha)
```{r}
ho = HoltWinters(dd1.ts, alpha=0.1, beta=F, gamma=F) #단순지수평활법
                #beta=F:no trend, gamma=F:no seasonal effect
ho
ho$fitted #xhat: 예측값
plot(ho)
```

 - 최적의 alpha를 찾아주는 경우
```{r}
#최적의 alpha: 예측오차와 관련된 MA,RMSE 등이 가장 작은 alpha -> HoltWinters가 스스로 찾아줌
ha = HoltWinters(dd1.ts, beta=F, gamma=F)
ha
ha$fitted
plot(ha) #red line이 fitted value => fitting값이 매우 유사
         #alpha가 작아지면서 변동성이 없어진 것을 알 수 있다
```

 - 잔차분석
```{r}
fa= forecast(ha)
names(fa) #fa의 component
fa$fitted
fa$residuals
tsdisplay(fa$residual)
Box.test(fa$residual, type="Box-Pierce") #H0:독립성이 있다. =>자기상관없다

#잔차에 대한 histogram
hist(fa$residual, 10, probability=T, col="light blue", 
     xlab="Time", ylab="Residuals",main="Histogram of Residuals")
points(density(fa$residuals[-1], bw=30), type='l', col="red", lwd=2)
title("\n \n - simple exponential smoothing")
```

 - 예측
```{r}
fa = forecast(ha, h=8)
fa #8개의 point에 대한 예측
accuracy(fa)

plot(forecast(ha, h=4)) +#forecast : 80%, 95% significant level
  lines(fa$fitted, col="red", lty=2, lwd=2) #fitted value

plot(forecast(ha, h=4, fan=T)) + #fan=T : 51%-99% significant level(현실적인 예측값을 볼 수 있다)
  lines(fa$fitted, col="red", lty=2, lwd=2)
```









